### PR TITLE
Add support for tags, improve code readability and allow controlling all timers with one call

### PR DESCRIPTION
**Pull request by XeduR**
Added support for adding tags to timers and for pausing/resuming/cancelling all timers (if no parameters are passed) or all timers with a specific tag (if a string is passed as the argument).

Some parameter names within functions were also changed to make the code easier to read.

Also updated the unit test file so that the new features can be tested.

---

A timer can be created by using the optional tag parameter:

timer.performWithDelay( [tag,] delay, listener, [iterations] )

If pause/cancel/resume is called without passing an argument, it will affect all timers. If the target is a string, the function will affect all timers with the given tag. If the target is a timerId, then the function will work as before, just affecting the given timer.

timer.pause( [target] ), timer.cancel( [target] ), timer.resume( [target] )

### CODE REVIEW

**Comment by Shchvova** [comment]
Great stuff. Great suggestion, however I have some comments on both implementation and on API. I would really like API to be unambiguous, and passing `tag` as an optional string parameters seems weird to me. This is not me trying to push my point, trying to have a discussion.

Here is one suggestion - add alternative `performWithDelay` syntax, which gets table instead of the 4 parameters 2 of which are optional. Like

```lua
timer.performWithDelay{ 
         delay = 2000,
         callback = function() print("Shine!") end,
         tag = "lights"
    }
```
Or may be move new parameter to the end? It just seems weird to have new optional first argument.
```lua
timer.performWithDelay(2000, function() print("Shine!") end, "lights")
-- or
timer.performWithDelay(2000, function() print("Shine!") end, nil, "lights")
```

About cancelling and resuming, everything seems rather fine. I am not sure if I would prefer this API to explicitly saying that timers should be paused by tag:
```lua
timer.pause { tag = 'lights' }
timer.pauseTag('lights')
```
Second one would resolve issue that pause/resume/cancel have return values, not meaningful in the tag version of function.

About implementation details: it seems that current implementation have a lot of code duplication. Like same code is used both pause/resume/cancel. Seems like almost same code used in two places, to perform operation on single timer, then on multiple.


I am really not trying to bash your code or ideas, but API design is extremely important. Once we push APIs to public, we won't change them if we'll find some flaw, because it would break peoples code and that is not something Corona does. We want our user's apps to continue working regardless of when they made them, especially if code frameworks are involved.
Lets try to think on it a little while.

**Comment by jcbnlsn** [comment]
I think timer.pause should follow the same logic as the transition library:
```
timer.pause( timerId )
timer.pause( tagName )
```

I like both:
```
timer.performWithDelay( [tag,] delay, listener, [iterations] )
timer.performWithDelay( delay, listener, [iterations],  [tag]  )
```

better than the table solution. That seems to big of a change to me.

**Comment by alanthomson** [comment]
Something to keep in mind is a problem I've run into before (admittedly due to poor management on my part). I was passing in something like this:

`timer.cancel(someTimerID) `

when someTimerID had been set to nil at some point (i.e. it was equivalent to calling timer.cancel() ). That led to all timers being cancelled which was not what I wanted, and brought the whole app to a stop.   

I realise you can't account for every developer mistake, but this is one reason why I'd prefer an explicit call to cancel all tags over leaving the argument blank.

**Comment by XeduR** [comment]
I agree that both approaches have their merits.

I also hadn't considered @alanthomson 's point about passing a timerId that is already nil. As such, I think that the simplest approach might be to use tag "all" in order to cancel/pause/resume all transitions.

**Comment by marksolar2d** [comment]
Agree with Alan. I think adding `timer.cancelAll()` is a better solution.

Also, I prefer not to have optionals first (makes no sense) and maybe this format is best of both worlds, won't break existing code and allows for easy extension in the future.

`timer.performWithDelay( delay, listener, [iterations],  [params] )`

Where params is a table containing` {tag = ''}`

**Comment by jcbnlsn** [comment]
@alanthomson 

I think you are mixing the timer library up with the transition library.

Calling timer.cancel(nil) doesn't cancel all timers. It throws an error:
`timer.cancel(): invalid timer (expected a table but got a nil)`

I  usually overwrite the timer.cancel call like this to avoid it:
```
local timerCancel = timer.cancel
timer.cancel = function(p)
    if p then timerCancel(p) end
end
```

**Comment by XeduR** [comment]
@jcbnlsn That is how it works now, but one of the proposed changes would have changed it to how @alanthomson had stated. I think that his point is correct and that it must be addressed by either creating a new function call for it or by requiring a tag like "all".

**Comment by alanthomson** [comment]
@jcbnlsn  Ah, I didn't mention in my first comment that this was using Jason Schroeder's timer2 library (had mentioned it on the Corona Slack), which works in a similar way to these proposed changes.

**Comment by jcbnlsn** [comment]
Ok. Then it makes sense. I think timer.cancelAll() would make sense then. 
I like the simplicity when not having the table approach.

**Comment by sporkfin** [comment]
@XeduR This is really cool and inspiring.  I'm on a slow C++ journey so I hope to contribute at some point as well.

I too like the format:
timer.performWithDelay( delay, listener, [iterations], [params] )

I assume that if there is no number entered for iterations but there is a params entry, iterations will default to 1?

**Comment by XeduR** [comment]
Yeah, the iterations would default to 1 if omitted.

Having reviewed the code and everyone's suggestions, I do agree that it would make more sense if the tag parameter was added to the end. I also think that while passing a table as an optional argument, like with transition framework, would have its benefits, just adding tag as the optional fourth parameter would be the better way forward.

I don't think that there needs to necessarily be a separate functions for controlling the tags, but one change that has to be changed is to at least require using the tag "all" to control all timers so that the users won't pause/cancel/resume all of their timers by accident.

Also, I agree with Vlad that I can reduce the code a bit by reusing some parts.

**Comment by agramonte** [comment]
optional tag parameter in the end or in a table is my vote.

**Comment by coronarob** [comment]
I have very mixed feelings about how to pass this parameter. There are numerous examples of Corona API's passing optional values as the first parameter. Just look at display.*. The first parameter is an optional "group" parameter. Passing it first is a very Corona way of doing things.

The other common example in Corona is display.newText() where you either pass it a list of parameters or a table of parameters. You don't want to make breaking changes to add this feature, so leaving timer.performWithDelay()'s existing parameters alone and checking to see if the first parameter is a table and if so, pull the values out of the table would fit an existing pattern. Transition.to() uses a table model for the core parameters. It would be nice if they shared a common pattern.

Adding optional parameters at the end is a very common pattern in other platforms. Most developers expect optional parameters to be at the end. 

This whole pass optionals first confused the bajeebies out of me when I first started. Other programming languages and libraries just don't do that. 

So I would go with an optional parameters table at the end of the list of parameters.

As far as cancelling, pausing and such. APIs for .pauseAll() .cancelAll() and .resumeAll() would be quite useful. For .pause(), .cancel() and .resume(), having not looked at the code (just the docs) it's expecting an object (i.e. table), so passing a table of parameters will be harder to manage and detect. A "string" would certainly be easy to detectable.

**Comment by XeduR** [comment]
**Alright everyone, my suggestion is as follows:**

I will add 3 new APIs: `timer.pauseAll()`, `timer.resumeAll()` and `timer.cancelAll()`. This way, there will be a simple and clear way to control all timers. This approach also eliminates the possibility of doing so accidentally as was the case with my previous suggestion.

For `timer.performWithDelay()`, I will add the optional tag parameter to the end, i.e.

`timer.performWithDelay( delay, listener [, iterations] [, tag] )`

For the 3 existing APIs: `timer.pause( timerId )`, `timer.resume( timerId  )` and `timer.cancel( timerId 
 )`, if the user passes a timerId, i.e. _a table_, then the API will control only said timer, as it does currently. If the user instead passes a tag, i.e. _a string_, then the API will control all timers which share that tag.

Finally, I will also prettify the code a bit so that there will be no unnecessary repetition.

Thoughts?

**Comment by marksolar2d** [comment]
That is my prefered solution! So yes, gets my vote.

**Comment by Shchvova** [comment]
Sounds good. Make sure code does not break existing applications as first priority.

**Pull request merged**
